# ---
# - hosts: bootstrap_host
#   become: true
#   tasks:
#     - name: Download & Setup Kubectl
#       get_url:
#         url: "https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl"
#         dest: "/usr/local/bin/kubectl"
#         mode: "a+x"

#     - name: Download & Setup eksctl
#       shell: curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
#       args:
#         executable: /bin/bash

#     - name: Move eksctl to /usr/local/bin
#       command: "sudo mv /tmp/eksctl /usr/local/bin"

#     - name: Save eksctl version
#       command: "/usr/local/bin/eksctl version"
#       register: eskctl_version

#     - name: Display eksctl version
#       debug:
#         var: eskctl_version.stdout_lines

#     - name: Build eks cluster
#       command: "/usr/local/bin/eksctl create cluster --name demo-cluster --region us-east-1 --nodegroup-name demo-nodes --node-type t2.micro --nodes 2 --nodes-min 1 --nodes-max 3"
#       register: eskctl_custer

#     - name: Display eks cluster
#       debug:
#         var: eskctl_custer.stdout_lines
