apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-pvc"
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  {{- range .Values.volumes.persistentVolumeClaim.accessModes }}
  - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.persistentVolumeClaim.storageCapacity }}