---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  {{- range $key, $value := .Values.awsLoadBalancer.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  name: {{ .Values.awsLoadBalancer.serviceAccountName }}
  namespace: {{ .Values.awsLoadBalancer.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.awsLoadBalancer.eksRoleName }}

