---
- name: First Host Playbook
  hosts: agent_host
  become: true
  tasks:
    - name: update apt package
      yum:
        update_cache: yes

    - name: Install Java-jdk 11
      apt:
        name: openjdk-11-jdk
        state: present
      ignore_errors: yes
      register: java_installation

    - name: Execute Java Version Command
      command: "java --version"
      ignore_errors: yes
      register: java_version

    - name: Display java version
      debug:
        var: java_version.stdout_lines     

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      ignore_errors: yes

    - name: Execute Docker Version Command
      command: "docker --version"
      ignore_errors: yes
      register: docker_version

    - name: Display docker
      debug:
        var: docker_version.stdout_lines 

    - name: Append user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
    - name: change docker.sock file permission
      file:
        path: /var/run/docker.sock
        mode: "0777"

- name: Second Host Playbook
  hosts: bootstrap_host
  become: true
  #become_user: ec2-user
  tasks:
    - name: Download AWS CLI Updated Version
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /opt
        remote_src: true

    - name: Install AWS CLI
      command: "sudo /opt/aws/install"
      register: aws_cli
      ignore_errors: yes

    - name: Display aws cli 
      debug:
        var: aws_cli.stdout_lines

    - name: Download & Setup Kubectl
      get_url:
        url: "https://s3.us-west-2.amazonaws.com/amazon-eks/1.25.13/2023-09-14/bin/linux/amd64/kubectl" #"https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: "a+x"
    #sed -i -e "s,client.authentication.k8s.io/v1alpha1,client.authentication.k8s.io/v1beta1,g" ~/.kube/config
    - name: Download & Setup eksctl
      shell: curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      args:
        executable: /bin/bash

    - name: Move eksctl to /usr/local/bin
      command: "sudo mv /tmp/eksctl /usr/local/bin"

    - name: Save eksctl version
      command: "/usr/local/bin/eksctl version"
      register: eskctl_version

    - name: Display eksctl version
      debug:
        var: eskctl_version.stdout_lines

    - name: Install helm if not exists
      unarchive:
        src: https://get.helm.sh/helm-v3.11.0-linux-amd64.tar.gz
        dest: /opt
        mode: "a+x"
        remote_src: true
      args:
        creates: /usr/local/bin/helm

    - name: Move Helm binary to /usr/local/bin
      command: "mv /opt/linux-amd64/helm /usr/local/bin/"
      args:
        creates: /usr/local/bin/helm

    - name: Print helm version
      command: "/usr/local/bin/helm version"
      register: helm_version

    - name: Display helm version
      debug:
        var: helm_version.stdout_lines

    - name: Deploy eks cluster
      command: "/usr/local/bin/eksctl create cluster --name demo-cluster --region us-east-1 --zones us-east-1a,us-east-1b --nodegroup-name demo-nodes --node-type t2.large --nodes 2 --nodes-min 1 --nodes-max 3"
      register: eskctl_cluster

    - name: Display eksctl cluster output
      debug:
        var: eskctl_cluster.stdout_lines

- name: Third Host Playbook
  hosts: bootstrap_host
  become_user: ec2-user
  tasks:
   - name: Fetch kubeconfig
     command: "aws eks update-kubeconfig --name demo-cluster --region us-east-1"
     
     ignore_errors: yes
   - name: "Fix error: exec plugin: invalid apiVersion client.authentication.k8s.io/v1alpha1"
     command: 'sed -i -e "s,client.authentication.k8s.io/v1alpha1,client.authentication.k8s.io/v1beta1,g" ~/.kube/config'
     ignore_errors: yes

   - name: Add aws-load-balancer-controller-eks repo
     command: "helm repo add eks https://aws.github.io/eks-charts"
     ignore_errors: yes
     
   - name: Install aws-load-balancer-controller (Operator)
     command: "helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=demo-cluster --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller"
     ignore_errors: yes

   - name: Copy file jenkins-0.1.0.tgz
     copy:
      src: /home/ec2-user/jenkins-0.1.0.tgz
      dest: /home/ec2-user/jenkins-0.1.0.tgz
      mode: "u+x"
     ignore_errors: yes

   - name: Copy file with regapp-0.1.0.tgz
     copy:
      src: /home/ec2-user/regapp-0.1.0.tgz
      dest: /home/ec2-user/regapp-0.1.0.tgz
      mode: "u+x"
     ignore_errors: yes
     
   - name: Install Jenkins Helm-Charts
     command: "helm install jenkins /home/ec2-user/jenkins-0.1.0.tgz --namespace=devops-tools --create-namespace"
     ignore_errors: yes
   - name: Install Registration App Helm-Charts
     command: "helm install regapp /home/ec2-user/regapp-0.1.0.tgz"
     ignore_errors: yes

